version: "2.1"

services:
  web:
    image: ghcr.io/bitfeed-project/bitfeed-client:2.1.3@sha256:861a70a049735717616cc5dfa480963a2adef31e937fdc34f6aa298e45eb3afc
    restart: on-failure
    stop_grace_period: 1m
    depends_on:
      - "api"
    environment:
      TARGET: "umbrel"
      BACKEND_HOST: "$APP_BITFEED_API_IP"
      BACKEND_PORT: "$APP_BITFEED_API_PORT"
    ports:
      - "$APP_BITFEED_PORT:80"
    networks:
      default:
        ipv4_address: $APP_BITFEED_IP

  api:
    image: ghcr.io/bitfeed-project/bitfeed-server:2.1.3@sha256:67e0357152a4f7fca067a32ca737c287521be16038936ed67b60a50558935b73
    user: "1000:1000"
    restart: on-failure
    stop_grace_period: 1m
    environment:
      PORT: "$APP_BITFEED_API_PORT"
      BITCOIN_HOST: "$BITCOIN_IP"
      BITCOIN_ZMQ_RAWTX_PORT: "$BITCOIN_ZMQ_RAWTX_PORT"
      BITCOIN_ZMQ_RAWBLOCK_PORT: "$BITCOIN_ZMQ_RAWBLOCK_PORT"
      BITCOIN_RPC_PORT: "$BITCOIN_RPC_PORT"
      BITCOIN_RPC_USER: "$BITCOIN_RPC_USER"
      BITCOIN_RPC_PASS: "$BITCOIN_RPC_PASS"
    volumes:
      - ${APP_DATA_DIR}/data:/app/data
    networks:
      default:
        ipv4_address: $APP_BITFEED_API_IP
